export enum TableActionTypes {
	GET_TABLE_DATA = "GET_TABLE_DATA",
	TABLE_STATE_CHANGED_TYPE = "TABLE_STATE_CHANGED_TYPE",
	GET_TABLE_DATA_START = "GET_TABLE_DATA_START",
	TABLE_DATA_ACTION_FAIL = "TABLE_DATA_ACTION_FAIL",
}
